name: Push (master)
on:
  push:
    branches: ["master"]
jobs:
  cf-wrangler:
    name: Deploy to Cloudflare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          secrets: |
            TOKEN_USER
            TOKEN_ADMIN
        env:
          TOKEN_USER: ${{ secrets.TOKEN_USER }}
          TOKEN_ADMIN: ${{ secrets.TOKEN_ADMIN }}
